JavaScript課題③-4
AIKIHIGASHI/task pull request #9
Opened 2020-08-28 13:43 UTC by AIKIHIGASHI

# what
JavaScript課題③-4の提出
タスク表示/非表示切り替え機能の追加

2020-08-29 12:39 UTC, myzktkyk requested changes
1点指摘をしました。

2020-08-29 12:39 UTC, myzktkyk commented on JS3-4.html
> +            const styleDisplayRoop = (array, value) => {
Type だと思われます。
```suggestion
            const styleDisplayLoop = (array, value) => {
```

2020-08-30 13:34 UTC, Dok1211 commented on JS3-4.html
> +                if (radio[0].checked) {
この実装だと、万が一radioボタンの順番が変わった場合実装が難しくなるので
何番目のボタンかではなく、どのボタンが押されたかで分岐するようにしましょう

2020-08-30 13:34 UTC, Dok1211 commented on JS3-4.html
> +                    if (radio[2].checked) {
ここも上記のコメントと同様です

2020-09-01 12:01 UTC, myzktkyk approved these changes
修正点を確認しました。
いいと思います！

2020-09-07 22:21 UTC, merged